# Generated by Django 2.1.7 on 2019-02-21 15:56

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('priority', todo.models.IntegerRangeField()),
            ],
            options={
                'ordering': ['-priority', 'dueDate', 'title'],
            },
        ),
    ]
